name: news
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  buildcondition: ^0.0.4
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hexcolor: ^2.0.3
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
